#!/usr/bin/python3.4

import sys
import devUtils.dirUtils as dirUtils
import devUtils.unitUtils as unitUtils


if __name__ == "__main__":
    if len(sys.argv) == 4:
        unitUtils.moveUnit(
            unitName   = sys.argv[1],
            fromSubdir = dirUtils.directify(sys.argv[2]),
            toSubdir   = dirUtils.directify(sys.argv[3]))
    else:
        print("usage: unit-name from-subdirectory to-subdirectory")
