#!/usr/bin/python3.4

import sys
import dev_utils.dir_utils as dir_utils
import dev_utils.unit_utils as unit_utils


if __name__ == "__main__":
    if len(sys.argv) == 4:
        unit_utils.move_unit(
            unit_name   = sys.argv[1],
            from_subdir = dir_utils.directify(sys.argv[2]),
            to_subdir   = dir_utils.directify(sys.argv[3]))
    else:
        print("usage: unit-name from-subdirectory to-subdirectory")
