#!/usr/bin/python3.4

import sys
import os
import devUtils.dirUtils as dirUtils
import devUtils.unitUtils as unitUtils


def splitUnitFileName(fileName, unitCB):
    unitFileName = fileName.rpartition(".")

    return unitCB(
        unitName      = unitFileName[0],
        fileExtension = unitFileName[1] + unitFileName[2])


def getAssociatedUnits(fromSubdir):
    associatedUnits = []

    def checkAddAssociatedUnit(unitName, fileExtension):
        def canAddUnit():
            return (
                dirUtils.isSourceFileExtension(fileExtension) and
                unitName not in associatedUnits)

        if canAddUnit():
            associatedUnits.append(unitName)

    for rootDir in dirUtils.ROOT_DIR_EXTENSIONS:
        for root, subdirs, fileNames in os.walk(rootDir + fromSubdir):
            for fileName in fileNames:
                splitUnitFileName(fileName, checkAddAssociatedUnit)

    return associatedUnits


def renameSubdir(fromSubdir, toSubdir):
    for associatedUnit in getAssociatedUnits(fromSubdir):
        unitUtils.moveUnit(associatedUnit, fromSubdir, toSubdir)


if __name__ == "__main__":
    if len(sys.argv) == 3:
        renameSubdir(
            fromSubdir = dirUtils.directify(sys.argv[1]),
            toSubdir   = dirUtils.directify(sys.argv[2]))
    else:
        print("usage: from-subdirectory to-subdirectory")

